<a href="https://colab.research.google.com/github/joohoshin/Python_Basic/blob/master/9_2_Numpy_%EA%B8%B0%EC%B4%88_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 배열 자동 생성
* random을 통해서 자동으로 생성가능함
* 이미 사용해본 random library와 문법은 비슷
* randint(start, end, size = (row size, column size)) 형태로 사용 (end는 포함되지 않음)

In [ ]:
import numpy as np

In [ ]:
arr1 = np.random.randint(0,10, size=(2,3))
print(arr1)

arr2 = np.random.randint(0,10, size = 10)
print(arr2)

[[7 3 3]
 [7 1 3]]
[7 3 0 9 8 2 6 2 5 7]


* rand(row size, column size)는 0~1 사이의 값을 랜덤 선택 (1은 미포함)


In [ ]:
arr3 = np.random.rand(5,3)
print(arr3)

[[0.3673078  0.67113084 0.41084182]
 [0.6591554  0.54608679 0.307241  ]
 [0.94875558 0.98581727 0.70140685]
 [0.83651209 0.65233588 0.28725514]
 [0.1437185  0.52422013 0.01348342]]


In [ ]:
arr4 = np.random.rand(5,3)
print(arr4)

[[0.08290824 0.28099184 0.26042219]
 [0.52064677 0.14993617 0.57444382]
 [0.82231193 0.3572519  0.79678102]
 [0.29484146 0.30593245 0.45897772]
 [0.56052333 0.47366557 0.98574375]]


* 그 외에도 여러가지 행렬 연산 기능이 있음
* https://www.bogotobogo.com/python/python_numpy_matrix_tutorial.php

##### 주요 통계값
* min(), count() 등을 쉽게 구할 수 있으며
* 평균 및 표준편차도 쉽게 구할 수 있다 mean(), std() 

In [ ]:
print(arr4.sum())
print(arr4.min())
print(arr4.max())
print(arr4.mean()) # 평균
print(arr4.std()) # 표준편차
print(arr4.var()) # 분산


6.925378136887134
0.08290823716580864
0.9857437453374569
0.4616918757924756
0.24764321265080844
0.06132716077201352


##### 특정 범위 가져오기
* arr[start:end:step]으로 특정 범위 데이터를 가져올 수 있다
  (end 는 미포함)
* 리스트와 동일함

In [ ]:
arr5 = np.random.randint(10, size = 10)
print(arr5)

[9 0 3 5 8 9 7 2 2 1]


In [ ]:
arr5[:5] #

array([9, 0, 3, 5, 8])

In [ ]:
arr5[1:3]

array([0, 3])